"""
Django settings for artion_backend project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from glob import glob

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(" ")
REVERSEPROXY = int(os.environ.get("REVERSEPROXY"))
REVERSEPROXYURL = os.environ.get("REVERSEPROXYURL")
SERVER_URL = os.environ.get("SERVER_URL")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # geodjango
    'django.contrib.gis',
    # leaflet maps
    'leaflet',
    # rest api
    "corsheaders",
    'rest_framework',
    'rest_framework.authtoken',
    # channels - sockets support
    'channels',
    # user apps
    'web',
    'mobile_api',
    'chat',
]

CORS_ALLOWED_ORIGINS = [
    'capacitor://localhost',
    'http://localhost',
    'http://localhost:8100',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
ROOT_URLCONF = 'artion_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'artion_backend.wsgi.application'
ASGI_APPLICATION = "artion_backend.asgi.application"
# ASGI_THREADS = default: number of CPUs * 5

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ['redis://redis:6379'],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

# NEEDED in order other applications can communicate with the restful api
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE',"Europe/Nicosia")

USE_I18N = True

USE_L10N = True

USE_TZ = True

GDAL_LIBRARY_PATH = glob('/usr/lib/libgdal.so.*')[0]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

USE_X_FORWARDED_HOST = int(os.environ.get("REVERSEPROXY"))

if DEBUG == 1:
    STATIC_URL = "/staticfiles/"
    LOGIN_REDIRECT_URL = "/"
    LOGIN_URL = "/login/"
    LOGOUT_URL = "/logout/"
    HOME_URL = "/"
    SESSION_TIMEOUT_REDIRECT = '/'
    FORCE_SCRIPT_NAME = "/"
else:
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    if REVERSEPROXY == 1:
        STATIC_URL = "/"+REVERSEPROXYURL+"/staticfiles/"
        LOGIN_REDIRECT_URL = "/" + REVERSEPROXYURL + "/"
        LOGIN_URL = "/" + REVERSEPROXYURL + "login/"
        LOGOUT_URL = "/" + REVERSEPROXYURL + "logout/"
        SESSION_TIMEOUT_REDIRECT = "/" + REVERSEPROXYURL
        FORCE_SCRIPT_NAME = "/" + REVERSEPROXYURL + "/"
        HOME_URL = FORCE_SCRIPT_NAME

        # SESSION_COOKIE_SECURE = True
        # CSRF_COOKIE_SECURE = True
    else:
        STATIC_URL = "/staticfiles/"
        LOGIN_REDIRECT_URL = "/dashboard/"
        LOGIN_URL = "/login/"
        LOGOUT_URL = "/logout/"
        SESSION_TIMEOUT_REDIRECT = "/"
        FORCE_SCRIPT_NAME = "/"
        HOME_URL = "/"

STATIC_ROOT = "/home/app/web/staticfiles"
LOGOUT_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FILE_UPLOAD_MAX_MEMORY_SIZE = 4096 * 1024

# ###### Leaflet settings ##########
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (35.14661, 33.45474),
    'DEFAULT_ZOOM': 9,
    'MIN_ZOOM': 6,
    'MAX_ZOOM': 17,
    'DEFAULT_PRECISION': 6,
    'ATTRIBUTION_PREFIX': None,  # 'Powered by django-leaflet',
    'MINIMAP': False,
    'TILES': [
        ('Open humanitarian Maps', 'https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {'attribution': '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}),
        ('Open Topo Maps', 'https://tile.opentopomap.org/{z}/{x}/{y}.png', {
            'attribution': 'Kartendaten: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>-Mitwirkende, SRTM | Kartendarstellung: &copy; <a href="https://opentopomap.org/">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'}),

    ]
}
# ###### Leaflet settings ##########
